config/routes.rb
Blocitoff::Application.routes.draw do
  resources :lists  do 
  	resources :items
  end 
  root :to => "lists#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list

	#validates :description, presence: true

	#validates :list, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  belongs_to :user

 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :list
  has_many :items, through: :list 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
   @list = List.find(params[:list_id])
    @items = @list.items

  end

  # GET /items/1
  # GET /items/1.json
  def show
        @list = List.find(params[:list_id])
        @item = Item.find(params[:id])

  end

  # GET /items/new
  def new
    @list = List.find(params[:list_id])
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
            @list = List.find(params[:list_id])

  end

  # POST /items
  # POST /items.json
  def create
    @list = List.find(params[:list_id])

     @item = Item.new(item_params)
    #@item =  current_user.item.build(params[:item])
    @item = current_user.items.build(item_params)
     #@item = current_user.items.build(params[:item])
    #@item.list = @topic
    #binding.pry

    respond_to do |format|
      if @item.save
        format.html { redirect_to [@list, @item], notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:completed, :description, :list, :user, :item)
    end

    #def more_than_seven_days_old
    #    current_time = Time.new
    #    if @item.created_at 
    # end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
 before_filter :authenticate_user!
 before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
     @list = List.find(params[:id])
     @items = @list.items
  end

  # GET /lists/new
  def new
    @list = List.new user_id: current_user.id
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:item_id, :user_id, :name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

app/views/items/_form.html.erb
<%= simple_form_for [list, item] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :completed %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', lists_items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table  class="table table-striped">
  <thead>
    <tr>
      <th>Completed</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @list.items.each do |item| %>
      sss
      <tr>
        <td><%= item.completed %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Show'%></td>
     

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_list_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render partial: 'form', locals: { list: @list, item: @item } %>

<%= link_to 'Back', list_items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Completed:</strong>
  <%= @item.completed %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 2.3 %>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <ul class="nav">
              <li><%= link_to 'Home', root_path %><li>
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blocitoff" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blocitoff" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="row">
  <div class="span6">
    <p>Guidelines for new Lists:</p>
    <ul class="list-group">
      <li class="list-group-item">Enter a name for you todo list</li>
      <li class="list-group-item">Blah blah blah</li>
      <li class="list-group-item">Blah blah blah</li>
      <li class="list-group-item">Blah blah blah</li>
    </ul>
  </div>
  <div class="span6">
    <%= form_for @list, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">

        <%= f.label :name, class: 'control-label' %>
        <div class="controls">
            <%= f.hidden_field :user_id, value: @list.user_id %>
            <%= f.text_field :name %>

        </div>
      </div>
      
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Create List", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists </h1>

<table "table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>dd</th>
      <th>ddd</th>
      <th><dd/th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.user.name %></td>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>
 

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>



<h1><%= @list.name %></h1>



<div class="row">
  <div class="span8">
    <% @items.each do |item| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to item.description, item %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="span4">
   <%= link_to "New Item", new_list_item_path(@list), class: 'btn btn-large btn-block' %>
  </div>



<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>



</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<%= link_to 'Edit account', edit_user_path %>